"""长期记忆 markdown 导出 + git 同步（0.4.0，圆桌决议 roundtable-20260812-mempool030）。

决议七条的落地：
①按 user_id 聚合单文件 ②单向导出（池唯一权威，md 只读快照）③事件/手动触发
④冲突不写 merge driver：pull 冲突时主文件取远端，本机版本落 .conflicts/ 并告警
⑤目录 memory/pool/<user_id>.md ⑥防手动编辑双护栏（git 脏检查中止 + 导出哈希
比对移 .edited.md）⑦文件头只读声明 + last-exported-at（UTC）

与决议的一处声明偏离：决议写「导出长期记忆到 memory/longterm/」，但固化调度
尚未接入服务进程（0.3.0 自查发现），longterm 层现实为空——只导 longterm 就是
形式交付。本实现导出**全部记忆**（按 tier 分节），目录相应改为 memory/pool/；
备份价值要求全量（faiss 损坏时 realtime 同样要能恢复）。固化上线后分节结构
天然兼容。

调用方式：
- CLI：mempool-export --user <id> --repo <nestwork仓库路径>（服务未起会自动拉起）
- 库：export_memories(...)（数据经 HTTP 取自服务进程，不违反单写者铁律）
"""
from __future__ import annotations

import hashlib
import json
import os
import socket
import subprocess
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

DEFAULT_SUBDIR = "memory/pool"
_STATE_FILE = "export-state.json"


# ---------------------------------------------------------------- 渲染（纯函数）

def _display_time(m: dict[str, Any]) -> str:
    """展示时间优先取原始时刻（reembed 迁移会重置 created_at，原值在 metadata）。"""
    meta = m.get("metadata") or {}
    return meta.get("orig_created_at") or m.get("created_at") or ""


def render_markdown(memories: list[dict[str, Any]], user_id: str, now_utc: str) -> str:
    """把一个 user 的全部记忆渲染成单文件 markdown（决议①⑦ + 偏离声明的分节）。"""
    longterm, realtime = [], []
    for m in memories:
        tier = (m.get("metadata") or {}).get("tier", "realtime")
        (longterm if tier == "longterm" else realtime).append(m)
    for bucket in (longterm, realtime):
        bucket.sort(key=_display_time)

    lines = [
        "<!-- READ-ONLY: generated by agent-memory-pool (mempool-export). -->",
        "<!-- 手动编辑不会回流进记忆池；下次导出时人工改动会被移到 .edited.md。 -->",
        f"<!-- last-exported-at: {now_utc} (UTC; 新旧判定依赖机器时钟，跨机注意漂移) -->",
        "",
        f"# 记忆池导出 · {user_id}",
        "",
        f"共 {len(memories)} 条（longterm {len(longterm)} / realtime {len(realtime)}）。",
        "池为唯一权威源，本文件是只读快照。",
        "",
    ]
    for title, bucket in (("长期记忆（longterm）", longterm), ("实时记忆（realtime）", realtime)):
        lines.append(f"## {title}")
        lines.append("")
        if not bucket:
            lines.append("（空）")
            lines.append("")
            continue
        for m in bucket:
            head = _display_time(m) or "unknown-time"
            agent = m.get("agent_id") or "unknown"
            run = m.get("run_id")
            suffix = f" · run:{run}" if run else ""
            lines.append(f"### {head} · {agent}{suffix}")
            lines.append("")
            lines.append((m.get("memory") or "").strip())
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------- 状态与哈希护栏

def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _body_hash(content: str) -> str:
    """变更检测哈希：剥掉带时间戳的头部行——否则每次导出时间戳都变，
    no_change 永远检测不出来（首版实测踩过）。"""
    body = "\n".join(
        line for line in content.splitlines() if "last-exported-at" not in line
    )
    return _sha256(body)


def _state_path() -> Path:
    root = Path(os.environ.get("MEMPOOL_DATA_ROOT", Path.home() / ".agent_memory_pool"))
    return root / _STATE_FILE


def _load_state() -> dict[str, Any]:
    try:
        return json.loads(_state_path().read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


def _save_state(state: dict[str, Any]) -> None:
    p = _state_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(state, ensure_ascii=False, indent=1), encoding="utf-8")


# ---------------------------------------------------------------- git

class ExportBlocked(RuntimeError):
    """护栏中止（如工作区脏）——不是 bug，是保护人工改动不被静默处理。"""


def _git(repo: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True, text=True, encoding="utf-8", errors="replace",
    )


def _git_ok(repo: Path, *args: str) -> None:
    r = _git(repo, *args)
    if r.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} 失败：{r.stderr.strip() or r.stdout.strip()}")


def _has_remote(repo: Path) -> bool:
    return bool(_git(repo, "remote").stdout.strip())


# ---------------------------------------------------------------- 主流程

@dataclass
class ExportResult:
    status: str                    # exported | no_change | conflict_isolated
    file: str
    edited_moved: Optional[str] = None
    conflict_file: Optional[str] = None
    warnings: list[str] = field(default_factory=list)


def export_memories(
    memories: list[dict[str, Any]],
    user_id: str,
    repo_dir: str | os.PathLike[str],
    *,
    subdir: str = DEFAULT_SUBDIR,
    push: bool = True,
) -> ExportResult:
    """把记忆列表导出到 git 仓库（决议②③④⑥的完整序列）。

    memories 由调用方提供（CLI 走 HTTP 从服务进程取，不碰数据库文件）。
    """
    repo = Path(repo_dir).resolve()
    if not (repo / ".git").exists():
        raise ExportBlocked(f"{repo} 不是 git 仓库——先 git init / clone")

    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    content = render_markdown(memories, user_id, now)
    target_rel = f"{subdir}/{user_id}.md"
    target = repo / target_rel
    target.parent.mkdir(parents=True, exist_ok=True)
    state = _load_state()
    state_key = f"{repo}|{user_id}"
    result = ExportResult(status="exported", file=str(target))

    # ⑥ 护栏一（必须在 pull 之前）：该文件有未提交人工改动 → 中止，绝不静默覆盖。
    # 放 pull 后会被 rebase 的「脏工作区拒绝」掩盖成假冲突（首版实测踩过）。
    dirty = _git(repo, "status", "--porcelain", "--", target_rel).stdout.strip()
    if dirty:
        raise ExportBlocked(
            f"{target_rel} 有未提交的本地改动，导出中止——"
            f"请先 commit（留档）或 checkout 丢弃，再重新导出"
        )

    # ③ 同步远端（决议：pull --rebase → 写 → commit → push）
    synced_remote = _has_remote(repo)
    if synced_remote:
        pull = _git(repo, "pull", "--rebase")
        if pull.returncode != 0:
            blob = (pull.stderr + pull.stdout).lower()
            if "conflict" not in blob:
                raise RuntimeError(f"git pull --rebase 失败（非冲突）：{pull.stderr.strip()}")
            # ④ 冲突路径：主文件取远端，本机版本隔离到 .conflicts/，不写 merge 逻辑
            _git(repo, "rebase", "--abort")
            merge = _git(repo, "pull", "-X", "theirs", "--no-rebase")
            if merge.returncode != 0:
                raise RuntimeError(f"冲突处理失败（pull -X theirs）：{merge.stderr.strip()}")
            stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
            conflict_rel = f"{subdir}/.conflicts/{user_id}-{socket.gethostname()}-{stamp}.md"
            conflict_file = repo / conflict_rel
            conflict_file.parent.mkdir(parents=True, exist_ok=True)
            conflict_file.write_text(content, encoding="utf-8")
            _git_ok(repo, "add", conflict_rel)
            _git_ok(repo, "commit", "-m", f"mempool: 冲突隔离 {user_id}（本机版本，主文件保留远端）")
            if push:
                _git_ok(repo, "push")
            result.status = "conflict_isolated"
            result.conflict_file = str(conflict_file)
            result.warnings.append(
                "双机导出冲突：主文件保留远端版本，本机版本在 .conflicts/ 待收编（池层合并 0.4.0 不做）"
            )
            return result

    # ⑥ 护栏二：哈希比对——已提交的人工改动移到 .edited.md 保全，主文件重新生成
    manual_edit = False
    if target.exists():
        actual = _sha256(target.read_text(encoding="utf-8"))
        recorded = (state.get(state_key) or {}).get("file_hash")
        if recorded != actual:
            manual_edit = True
            edited = target.with_name(f"{user_id}.edited.md")
            if edited.exists():
                stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
                edited = target.with_name(f"{user_id}.edited-{stamp}.md")
            target.rename(edited)
            result.edited_moved = str(edited)
            result.warnings.append(
                f"检测到主文件被改动过（或首次接管已有文件），原文件已保全为 {edited.name}；"
                f"如需回存池请人工执行 add_memory"
            )

    # 变更检测：正文（剥时间戳行）没变且无人工改动 → 完全跳过（不写盘不 commit）
    recorded_body = (state.get(state_key) or {}).get("body_hash")
    if target.exists() and not manual_edit and recorded_body == _body_hash(content):
        result.status = "no_change"
        return result

    # ② 写只读快照 + 记录哈希
    target.write_text(content, encoding="utf-8")
    state[state_key] = {
        "file_hash": _sha256(content),
        "body_hash": _body_hash(content),
        "exported_at": now,
    }
    _save_state(state)

    # commit（无 diff 自动跳过）+ push
    _git_ok(repo, "add", "--", target_rel)
    if result.edited_moved:
        _git_ok(repo, "add", "--", str(Path(result.edited_moved).relative_to(repo)))
    staged = _git(repo, "diff", "--cached", "--quiet")
    if staged.returncode != 0:  # 有 staged 变化
        _git_ok(repo, "commit", "-m", f"mempool: 导出 {user_id}（{len(memories)} 条，{now}）")
        if push and synced_remote:
            _git_ok(repo, "push")
    else:
        result.status = "no_change"
    return result


def main() -> None:
    """CLI 入口：mempool-export --user <id> --repo <git仓库>。"""
    import argparse

    parser = argparse.ArgumentParser(description="记忆池 markdown 导出 + git 同步")
    parser.add_argument("--user", required=True, help="user_id（共享边界）")
    parser.add_argument(
        "--repo",
        default=os.environ.get("MEMPOOL_EXPORT_REPO", ""),
        help="目标 git 仓库路径（或环境变量 MEMPOOL_EXPORT_REPO；建议私有 nestwork 仓库）",
    )
    parser.add_argument("--subdir", default=DEFAULT_SUBDIR, help=f"仓库内目录（默认 {DEFAULT_SUBDIR}）")
    parser.add_argument("--no-push", action="store_true", help="只 commit 不 push")
    parser.add_argument("--limit", type=int, default=1000, help="最多导出条数（默认 1000）")
    args = parser.parse_args()
    if not args.repo:
        parser.error("--repo 未指定且 MEMPOOL_EXPORT_REPO 未设置")

    # 数据经 HTTP 取自服务进程（单写者铁律：本进程不碰数据库文件；服务没起自动拉起）
    from memorypool.client_sdk import MemoryPoolClient

    client = MemoryPoolClient()
    memories = client.list(user_id=args.user, limit=args.limit)
    r = export_memories(
        memories, args.user, args.repo, subdir=args.subdir, push=not args.no_push
    )
    print(f"status={r.status}  file={r.file}  count={len(memories)}")
    for w in r.warnings:
        print(f"warning: {w}")
    if r.edited_moved:
        print(f"edited -> {r.edited_moved}")
    if r.conflict_file:
        print(f"conflict -> {r.conflict_file}")


if __name__ == "__main__":
    main()
